### ISSUE TITLE
Issue with Helmet in React.lazy component on React 18.0.0

### ISSUE THREAD

**Issue by KyleJune** [staylor/react-helmet-async#169]
I have my app wrapped in a helmet provider.

```jsx
<HelmetProvider><App/></HelmetProvider>
```

The app is pretty straight forward, It has a defaultTitle and a titleTemplate. The Pages component has page views where each page has a helmet tag.

```jsx
export const App = () => (
  <div id="app">
    <Helmet defaultTitle="App" titleTemplate="App - %s">
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    </Helmet>
    <Navigation />
    <Pages />
  </div>
);
```

It works as expected for pages that are not lazy loaded. In the attached video, you can see it updating correctly when navigating between the Home and About pages. The Tenants page is lazy loaded and just has a helmet tag with a title tag in it. The Tenant pages are lazy loaded too when you click on one from the Tenants page.

When the lazy Tenants component tries to update the title to Tenants, unlike the About and Home page, it does not use the titleTemplate. In addition to that, it ends up not even using the title and instead changing the title to the defaultTitle of just "App". The expected behavior is for the title to change to "App - Tenants".

Then when I try navigating back to the Home and About pages, they no longer have any affect on the title.

Afterward, when I navigate to any of the lazy Tenant components, the title updates to the name of the tenant. The expected behavior is for the title to change to "App - {Name of tenant here}".

Afterwards, at some point the title starts changing to "Tenants" when navigating back and forth between the Tenants page and the individual Tenant pages.

I'm not getting any errors in Dev tools console. The issue happens in both Chrome and Firefox. The video below is in Chrome.

https://user-images.githubusercontent.com/3241653/164953327-9e1df573-d72f-4f94-895d-afed2d4161b5.mp4

**Comment by KyleJune** [comment]
On the same app, if I just switch to loading the components statically instead of using lazy loading, it works. Here is a video of that.

https://user-images.githubusercontent.com/3241653/164953809-38e59ffe-9fdb-4ddb-b393-c890ac44dbf0.mp4

I thought maybe the issue might be that providers outside of lazy are not accessible to consumers within the lazy component but that was not true. When I tested that theory creating my own context and having it add something to the page, the Tenants page was correctly getting the value from the Provider on the application. The issue appears to be with Helmet.

**Comment by KyleJune** [comment]
I'm using esbuild to create my bundles in esm format. My only theory right now is that maybe there is state being stored somewhere other than the provider that cannot be accessed from different esm modules.

**Comment by KyleJune** [comment]
I created a minimal reproduction path for this issue. After further testing, it appears the issue is related to both the usage of Suspense and React.lazy together. Instructions on how to build the bundle and run the file server can be found in the readme on github.

Github: https://github.com/KyleJune/react-helmet-async-issue
Deployment: https://cold-rook-31.deno.dev/

To run on your local machine, you need to have Deno 1.21.0 installed. If you click the Deployment url above, you can see the example from that repository live without having to install deno.

If I switch between A and B there are no issues but as soon as I switch to C, it gets stuck with the default title.

https://user-images.githubusercontent.com/3241653/164989861-72ab1387-a35c-494f-893f-908145f3c8cf.mp4

If I do the same but then switch to D, both the defaultTitle and titleTemplate are ignored.

https://user-images.githubusercontent.com/3241653/164990058-7cb706d4-0bb6-4d08-8a83-bec9164d4a65.mp4

Neither issue presents itself if I first navigate to component C. As long as I navigate to C and D before A and B, the first issue won't present itself.

https://user-images.githubusercontent.com/3241653/164989967-38342b17-c94b-406c-ab23-25137c0af723.mp4

If I navigate to D first, then A or B, the first issue presents itself but the second issue doesn't.

https://user-images.githubusercontent.com/3241653/164990110-26dbc45f-f2b3-42f8-83b0-ddb78b7bec04.mp4

**Comment by KyleJune** [comment]
Looks like this issue is resolved in 18.1.0 which was released today. I just tested it.

**Comment by CaliforniaMountainSnake** [comment]
Updating to the `18.1.0` of React did not fix the issue for me.
But I solved this problem when I rewrote my code to exclude `React.lazy` and use native webpack's lazy imports.
